import React from 'react';

interface FeatureItem {
  id: number;
  title: string;
  description: string;
  icon: React.ReactNode;
}

const Features: React.FC = () => {
  const featuresList: FeatureItem[] = [
    {
      id: 1,
      title: "Career Assessment",
      description: "Discover your cognitive strengths, personality traits, and skill levels through our scientifically-backed assessments.",
      icon: (
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"></path>
          <polyline points="14 2 14 8 20 8"></polyline>
          <line x1="16" y1="13" x2="8" y2="13"></line>
          <line x1="16" y1="17" x2="8" y2="17"></line>
          <polyline points="10 9 9 9 8 9"></polyline>
        </svg>
      )
    },
    {
      id: 2,
      title: "AI Career Recommendations",
      description: "Receive tailored career options and custom pathway roadmaps generated by our advanced matching engines.",
      icon: (
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <path d="M12 2v2M12 20v2M4.93 4.93l1.41 1.41M17.66 17.66l1.41 1.41M2 12h2M20 12h2M6.34 17.66l-1.41 1.41M19.07 4.93l-1.41 1.41"></path>
          <circle cx="12" cy="12" r="4"></circle>
        </svg>
      )
    },
    {
      id: 3,
      title: "Mentor Matching",
      description: "Connect with verified industry experts and academic guides who provide personalized, real-world advice.",
      icon: (
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
          <circle cx="9" cy="7" r="4"></circle>
          <path d="M23 21v-2a4 4 0 0 0-3-3.87"></path>
          <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
        </svg>
      )
    },
    {
      id: 4,
      title: "Skill Development Tracking",
      description: "Map out the specific credentials, courses, and soft skills required for your dream job and monitor your growth.",
      icon: (
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <circle cx="12" cy="12" r="10"></circle>
          <circle cx="12" cy="12" r="6"></circle>
          <circle cx="12" cy="12" r="2"></circle>
        </svg>
      )
    },
    {
      id: 5,
      title: "Learning Resources",
      description: "Access curated articles, templates, interactive roadmaps, and masterclasses tailored to your goals.",
      icon: (
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"></path>
          <path d="M4 4.5A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1-2.5-2.5V4.5z"></path>
        </svg>
      )
    },
    {
      id: 6,
      title: "Progress Dashboard",
      description: "Visualize your developmental timeline, manage mentorship schedules, and track application progress.",
      icon: (
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
          <line x1="18" y1="20" x2="18" y2="10"></line>
          <line x1="12" y1="20" x2="12" y2="4"></line>
          <line x1="6" y1="20" x2="6" y2="14"></line>
        </svg>
      )
    }
  ];

  return (
    <section id="features" className="sh-section sh-features">
      <div className="sh-container">
        <div className="sh-section-title-wrap">
          <span className="sh-section-subtitle">Features</span>
          <h2 className="sh-section-title">Everything You Need To Plan Your Future</h2>
          <p className="sh-section-description">
            We provide students with a comprehensive, data-driven system to navigate the transition from school to career.
          </p>
        </div>

        <div className="sh-features-grid">
          {featuresList.map((feature) => (
            <div key={feature.id} className="sh-feature-card">
              <div className="sh-feature-icon">
                {feature.icon}
              </div>
              <h3 className="sh-feature-title">{feature.title}</h3>
              <p className="sh-feature-desc">{feature.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Features;
